#==================================================================================#
# Basic configuration                                                              #
#==================================================================================#
Material:
  Item: GOLD_HOE
  Name: '&4*&c*&4* &c&lSickle &4*&c*&4* &7(Right Click)'
  # Attribute = true  -> Hide the attributes of your item
  # Attribute = false -> Leave attributes visible from your item
  Attribute: true
  Lore:
    - '&7Pick up and replanted your plantings automatically.'

Configuration:
  # Drop = true  -> Items will launch on the ground.
  # Drop = false -> Items will be automatically put in the player's inventory.
  Drop: true
  # Content = true  -> When a player picks up a plant, he must have this plant in the inventory.
  # Content = false -> When the player picks up a plant, the plant will replant automatically.
  Content: false
  #==================================================================================#
  # List of allowed action break:                                                    #
  # RIGHT_CLICK_BLOCK, LEFT_CLICK_BLOCK                                              #
  #==================================================================================#
  Break: RIGHT_CLICK_BLOCK
  #==================================================================================#
  # List of allowed durability:                                                      #
  # MESSAGE : Send plugin messages to the player's chat                              #
  # ACTIONBAR : Send plugin messages to the player's actionbar                       #
  #==================================================================================#
  Message: "MESSAGE"

Permission:
  Commands: 'depthsickle.commands'
  Use: 'depthsickle.use'

Plugin:
  McMMO:
    Experiences:
      CARROT: 50
      POTATO: 50
      BEETROOT_BLOCK: 50
      CROPS: 50
      NETHER_WARTS: 50
      MELON_BLOCK: 20
      PUMPKIN: 20

  Factions:
    #==================================================================================#
    # List of allowed Faction's plugins :                                              #
    # SavageFactions, None                                                             #
    #==================================================================================#
    Plugin: None

#==================================================================================#
# List of allowed materials :                                                      #
# CARROT, POTATO, BEETROOT_BLOCK, CROPS, NETHER_WARTS, MELON_BLOCK, PUMPKIN        #
#==================================================================================#
Plants:
  - CARROT
  - POTATO
  - BEETROOT_BLOCK
  - CROPS
  - NETHER_WARTS
  - MELON_BLOCK
  - PUMPKIN

#==================================================================================#
# List of allowed worlds                                                           #
#==================================================================================#
Worlds:
  - world
  - world_nether
  - world_the_end