#======================================================================================#
#                                                                                      #
#                       DepthSickle created by xStalkers.                              #
#                   https://www.mc-market.org/resources/13283/                         #
#     https://www.spigotmc.org/resources/depthsickle-automate-your-farms.70511/        #
#                                                                                      #
#======================================================================================#

Material:
  Item: GOLD_HOE
  Name: '&4*&c*&4* &c&lSickle &4*&c*&4* &7(Right click)'
  #======================================================================================#
  # Attribute = true : Hide the attributes of your item.                                 #
  # Attribute = false : Leave attributes visible from your item.                         #
  #======================================================================================#
  Attribute: true
  Lore:
    - '&fAutomate your crops on your farms.'

Permission:
  #======================================================================================#
  # COMMAND : Permission to use commands.                                                #
  # USE : Permission to use the sickle.                                                  #
  #======================================================================================#
  Command: 'depthsickle.command'
  Bypass: 'depthsickle.bypass'
  Use:
    Harvest: 'depthsickle.mod.harvest'
    Autosell: 'depthsickle.mod.autosell'

Configuration:
  #======================================================================================#
  # If Drop is true, the items will drop to the ground.                                  #
  # If Drop is false, the items will automatically be in the player's inventory.         #
  #======================================================================================#
  Drop: true
  #======================================================================================#
  # If Content is in true, a seed will ask the player to replant the crop .              #
  # If Content is false, a seed will be given automatically to replant.                  #
  #======================================================================================#
  Content: false
  #======================================================================================#
  # List of allowed to send messages:                                                    #
  # COMMON : Send messages to the player's chat                                          #
  # ACTIONBAR : Send messages to the player's actionbar                                  #
  #======================================================================================#
  Message: 'COMMON'
  #======================================================================================#
  # List of allowed action:                                                              #
  # RIGHT_CLICK_BLOCK, LEFT_CLICK_BLOCK                                                  #
  #======================================================================================#
  Action: RIGHT_CLICK_BLOCK

Hook:
  McMMO:
    CARROT: 50
    POTATO: 50
    BEETROOT_BLOCK: 50
    CROPS: 50
    NETHER_WARTS: 50
    MELON_BLOCK: 20
    PUMPKIN: 20
  Economy:
    #======================================================================================#
    # ShopGUIPlus = true : Will used the prices available in the ShopGUIPlus plugin shop.  #
    # ShopGUIPlus = false : Will used prices later configure.                              #
    #======================================================================================#
    ShopGUIPlus: false
    #======================================================================================#
    # zShop = true : Will used the prices available in the zShop plugin shop.              #
    # zShop = false : Will used prices later configure.                                    #
    #======================================================================================#
    zShop: false
    Price:
      CARROT: 1
      POTATO: 1
      BEETROOT_BLOCK: 1
      CROPS: 1
      NETHER_WARTS: 1
      MELON: 0.75
      PUMPKIN: 0.75
  Faction:
    #======================================================================================#
    # List of allowed Faction's plugins :                                                  #
    # SavageFactions, None                                                                 #
    #======================================================================================#
    Plugin: 'none'

#======================================================================================#
# List of allowed crops :                                                              #
# CARROT, POTATO, BEETROOT_BLOCK, CROPS, NETHER_WARTS, MELON_BLOCK, PUMPKIN            #
#======================================================================================#
Crop:
  - CARROT
  - POTATO
  - BEETROOT_BLOCK
  - CROPS
  - NETHER_WARTS
  - MELON_BLOCK
  - PUMPKIN

#======================================================================================#
# List of allowed worlds                                                               #
#======================================================================================#
World:
  - world
  - world_nether
  - world_the_end