name: DepthSickle
version: 1.1.0.4
author: xStalkers
main: fr.depthsickle.net.Main
softdepend: [zShop]
commands:
  depthsickle:
    description: A command adde for DepthSickle's plugin
    aliases: [ds,sickle]